### ISSUE TITLE
Devolución

### ISSUE THREAD

**Issue by LeandroLopezsv** [JhonatanSoto/Mercado-Liebre#1]
Hola Jhona!
Es casi de maleducado hacerte correcciones a vos q la tenes tan clara, pero es tarea... y va con la mejor de las ondas.

Se nota mucho trabajo en lo visual, me encantó el carrusel, le suma mucho al home.
En el home, al hacer hover, no muestra el nombre del producto, y no logré ingresar desde los iconos del header ni a register ni a login.
Lo hice cargando la página al localhost, y pude verlas.
En register al clickear el botón enviar me da error (quizás lo hace en mi máquina, si querés me ofrezco para que nos juntemos y lo veamos juntos), y en login, no da error, pero no vuelve al home (tampoco lo hace con click en el logo del header).

Son solo detalles mínimos de percepción o visiones diferentes, en si, tu MercadoLiebre está muy bien logrado. APLAUSOS PARA TU LABURO JHONA!!

**Comment by JhonatanSoto** [comment]
gracias lean, si me habia olvidado linkear todas las rutas hacia las otras vistas y lo de nombre del producto lo habia hecho pero no se por que no se subio , gracias por tu corrrecion !! despues me pasare a ver tu mercado liebre. saludos.

**Comment by LeandroLopezsv** [comment]
Espero ayude y aporte, ya q más allá q es una actividad q nos piden, la
idea es SUMAR
